services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-triage-api
    env_file: .env
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
